### ISSUE TITLE
atp.ts getPostの処理

### ISSUE THREAD

**Issue by ShinoharaTa** [penpenpng/skylight#8]
もしかしたら、
https://github.com/penpenpng/skylight/blob/main/src/lib/atp.ts

getPostの内部処理が間違っているかも。
responseがundefinedになってしまっていた

実装は僕の方で書き直してるこちらを参照されたし

https://github.com/ShinoharaTa/AozoraWebClient/blob/develop/plugins/atp.ts

```typescript
  async getPost(params: { uri: string }) {
    const response = await this.getPostThread({ ...params, depth: 0 })
    if (!response.thread.notFound) {
      return response.thread.post
    } else {
      return null
    }
  }
  async getPostThread(params: { uri: string; depth?: number }) {
    const { success, data } = await this.agent.api.app.bsky.feed.getPostThread(
      params
    )
    return success ? data : null
  }
```

**Comment by penpenpng** [comment]
たぶん現行のバージョンは正しく動いていそうなのでいつの間にか直っていたかも？ https://github.com/penpenpng/skylight/blob/7b3bd4fe9323232f90c0f5599c7db5a37e6ed3dd/src/lib/atp.ts#L259-L281

**Comment by ShinoharaTa** [comment]
正しく動いてそうでした！
